server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # tomcat默认大小2M,超过2M的文件不会被捕获,需要调整此处大小为100MB或者-1
spring:
  profiles:
    active: prod
  banner:
    location: classpath:banner/banner.txt
  servlet:
    multipart:
      max-file-size: 5MB # 文件上传大小限制
      max-request-size: 5MB # 文件最大请求限制

# 日志级别
logging:
  level:
    root: info

# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true