server:
  port: 8099
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # tomcat默认大小2M,超过2M的文件不会被捕获,需要调整此处大小为100MB或者-1
spring:
  profiles:
    active: dev
  banner:
    location: classpath:banner/banner.txt
  servlet:
    multipart:
      max-file-size: 2MB # 文件上传大小限制,设置最大值,超过该值报错
      max-request-size: 2MB # 文件最大请求限制,用于批量上传
