server:
  port: 8099
  
spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型
    driver-class-name: com.mysql.jdbc.Driver      # mysql数据库驱动类名称
    url: jdbc:mysql://192.168.1.1:3306/mock_douyin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间/ms
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长/ms,超时则会被释放
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长/ms,超时则会被释放
      connection-test-query: SELECT 1
  mail:
    host: smtp.163.com
    username: 发送邮箱
    password: 授权码
    port: 25
    default-encoding: UTF-8
    protocol: smtp